version: '2'
services:
    euroshini-app:
        image: euroshini
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://euroshini-postgresql:5432/euroshini
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=euroshini-elasticsearch:9300
        ports:
            - 8080:8080
    euroshini-postgresql:
        extends:
            file: postgresql.yml
            service: euroshini-postgresql
    euroshini-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: euroshini-elasticsearch
